-- =============================================================================
-- Migration 001: Core Tables for Realive
-- 
-- WHAT IS THIS?
-- SQL is the language used to create and manage database tables.
-- This file defines the exact structure of our data.
-- We run it once in the Supabase SQL Editor.
--
-- Run order: execute this entire file top to bottom.
-- =============================================================================


-- =============================================================================
-- TABLE: pipeline_runs
-- 
-- Every time Realive receives a CI failure webhook, a pipeline_run record is
-- created. This is the central record that tracks the entire lifecycle of a
-- fix attempt — from "we just received a failure" to "fix delivered to GitHub".
-- =============================================================================
CREATE TABLE IF NOT EXISTS pipeline_runs (
    -- Primary key: a UUID auto-generated by the database
    -- (UUID = Universally Unique ID, like: "550e8400-e29b-41d4-a716-446655440000")
    id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Timestamps: automatically managed
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ── Where did this failure come from? ─────────────────────────────────────
    repo_full_name         TEXT NOT NULL,        -- e.g. "drizzle-org/my-service"
    pr_number              INTEGER NOT NULL,     -- e.g. 415
    commit_sha             TEXT NOT NULL,        -- the git commit that triggered CI

    -- ── What is the current state of this run? ────────────────────────────────
    -- Status flows: CLASSIFYING → WAITING_FOR_APPROVAL → FIXING → FIX_DELIVERED
    --                          ↘ STOPPED (if not a test mismatch)
    --                                                  ↘ FIX_FAILED (if retry fails)
    status                 TEXT NOT NULL DEFAULT 'CLASSIFYING',

    -- ── Populated by the Classifier node (Milestone 4) ───────────────────────
    failure_category       TEXT,        -- TEST_MISMATCH | APP_BUG | ENV_CONFIG | FLAKY | UNCLASSIFIABLE
    classification_reason  TEXT,        -- Plain English explanation for the dashboard
    failure_info           JSONB,       -- Structured parsed failure: {file, function, line, error}

    -- ── Populated by HITL Gate / Fixer (Milestones 5-6) ─────────────────────
    user_hint              TEXT,        -- Optional hint typed by developer
    patch_diff             TEXT,        -- The unified diff shown in the Monaco viewer
    stop_reason            TEXT,        -- Why we stopped (if status = STOPPED or FIX_FAILED)
    retry_count            INTEGER NOT NULL DEFAULT 0,

    -- ── Repo configuration ───────────────────────────────────────────────────
    mode                   TEXT NOT NULL DEFAULT 'MANUAL',  -- MANUAL | AUTOPILOT

    -- ── Constraints: enforce valid values at the DB level ────────────────────
    CONSTRAINT valid_status CHECK (status IN (
        'CLASSIFYING', 'WAITING_FOR_APPROVAL', 'FIXING',
        'FIX_DELIVERED', 'FIX_FAILED', 'STOPPED', 'DISMISSED'
    )),
    CONSTRAINT valid_mode CHECK (mode IN ('MANUAL', 'AUTOPILOT')),
    CONSTRAINT valid_category CHECK (failure_category IN (
        'TEST_MISMATCH', 'APP_BUG', 'ENV_CONFIG', 'FLAKY', 'UNCLASSIFIABLE'
    ) OR failure_category IS NULL)
);

-- Index: the dashboard will frequently query by repo + recent runs
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_repo ON pipeline_runs(repo_full_name, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_status ON pipeline_runs(status);


-- =============================================================================
-- TABLE: fix_history
-- 
-- An immutable audit log. Every significant action Realive takes is recorded
-- here. This means you can always answer: "what exactly happened to run X?"
--
-- IMMUTABLE = records are never updated, only inserted. This is intentional.
-- =============================================================================
CREATE TABLE IF NOT EXISTS fix_history (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Foreign key: links to the pipeline_run this action belongs to
    -- ON DELETE CASCADE = if the run is deleted, its history is too
    run_id      UUID NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,

    -- What happened?
    -- Examples: WEBHOOK_RECEIVED, CLASSIFIED, APPROVED, DISMISSED,
    --           FIX_ATTEMPTED, FIX_VALIDATED, FIX_DELIVERED, FIX_FAILED
    action      TEXT NOT NULL,

    -- Who did it? 'realive[bot]' for automated actions, user identity for approvals
    actor       TEXT NOT NULL DEFAULT 'realive[bot]',

    -- Any extra data relevant to this action (flexible JSON blob)
    details     JSONB
);

CREATE INDEX IF NOT EXISTS idx_fix_history_run_id ON fix_history(run_id, created_at DESC);


-- =============================================================================
-- TRIGGER: auto-update updated_at on pipeline_runs
--
-- WHAT IS A TRIGGER?
-- A trigger is a function that the database calls automatically when something
-- happens. This one fires every time a pipeline_run row is updated, and
-- sets updated_at to the current time. So you never need to set it manually.
-- =============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER set_pipeline_runs_updated_at
    BEFORE UPDATE ON pipeline_runs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();


-- =============================================================================
-- REALTIME: Enable live updates on pipeline_runs
--
-- WHAT IS REALTIME?
-- Supabase can push row changes (INSERT, UPDATE, DELETE) to connected clients
-- over a WebSocket in real time. We enable this on pipeline_runs so the React
-- dashboard updates instantly when a run's status changes — no polling needed.
-- =============================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE pipeline_runs;


-- Verification: these should return 0 rows (tables are empty, just created)
SELECT COUNT(*) AS pipeline_runs_count FROM pipeline_runs;
SELECT COUNT(*) AS fix_history_count FROM fix_history;
